In [5]:
import numpy as np

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [51]:
N = 10

In [63]:
b = np.arange(N-1,-1,-1)
print(b)
type(b)

[9 8 7 6 5 4 3 2 1 0]


numpy.ndarray

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [55]:
n = 10

In [56]:
c = np.diag(np.arange(n-1,-1,-1),k=0)

In [57]:
c

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
np.trace(c)

45

Задание 3
Решите систему уравнений:
4x + 2y + z = 4,
x + 3y = 12,
5y + 4z = -3.

In [61]:
d = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
e = np.array( [4, 12, -3] )
np.linalg.solve(d, e)


array([ 0.46666667,  3.84444444, -5.55555556])

Задание 4. Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array

In [75]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [76]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [94]:
import matplotlib.pyplot as plt

In [83]:
for i,l in enumerate(users_stats):
    w = np.linalg.norm(l)
    z = np.linalg.norm(next_user_stats)
    f = np.dot(l,next_user_stats) / (w * z)
    print(i+1,f)

1 0.19999999999999996
2 0.8451542547285165
3 0.3999999999999999
4 0.7905694150420948
5 0.3999999999999999
6 0.0
7 0.0
8 0.9486832980505138
9 0.0
10 0.0


In [85]:
id_ = 1
dict_={}

In [96]:
for i,l in enumerate(users_stats):
    w = np.linalg.norm(l)
    z = np.linalg.norm(next_user_stats)
    f = np.dot(l,next_user_stats) / (w * z)
    m = {id_:f}
    dict_.update(m)
    id_=id_+1
    
max_similarity = max(dict_, key=dict_.get)
print(f'Самый похожий пользователь имеет ID = ',max_similarity)
   

Самый похожий пользователь имеет ID =  8
